# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{swiffer}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Browne"]
  s.date = %q{2010-03-31}
  s.description = %q{A Project Building Tool for Actionscript Development}
  s.email = %q{me@petebrowne.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/swiffer.rb",
     "lib/swiffer/base.rb",
     "lib/swiffer/library.rb",
     "lib/swiffer/project.rb",
     "lib/swiffer/templates/launch.xml.erb",
     "spec/library_spec.rb",
     "spec/project_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "swiffer.gemspec"
  ]
  s.homepage = %q{http://github.com/peterbrowne/swiffer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Project Building Tool for Actionscript Development}
  s.test_files = [
    "spec/project_spec.rb",
     "spec/library_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0.5.4"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0.5.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0.5.4"])
  end
end

